### ISSUE TITLE
not working again

### ISSUE THREAD

**Issue by martha435** [bubach/AdfreePlay#3]
Hey, love your work! It has been really useful.

However it does not work at the moment on i.e. viafree and tv4play. Would appreciate an update!

**Comment by bubach** [comment]
fixed.

**Comment by martha435** [comment]
Hmm it still doesn't seem to work at tv4play? Don't know if it's because you need to have a user to be able to watch the episodes (and therefore they know that you don't have premium). 

However viafree is working perfectly, thanks!

**Comment by bubach** [comment]
fixed, now also on google web store @
https://chrome.google.com/webstore/detail/adfreeplay/nhkpipalpkhpemgeaekkcdacobgdflnn

**Comment by martha435** [comment]
I got this weird playback at tv4play, where the sound from the ads run at the same time as the actual episode run with both video and sound. So it's like two audiofiles are playing at the same time - overlapped.

About the availability on google web store, don't you think that will increase the attention from the websites to start "preventing" your adfix?

Really appreciate your work! Cheers

**Comment by bubach** [comment]
Do you have this issue on all tv4 videos? What version of chrome?  windows or mac? if you have any specific links to videos where this problem exists I can take a look, but all my random tests work fine for me.

**Comment by Welixanne** [comment]
I have the same problem on this specific series/url: http://www.tv4play.se/program/bachelor-n%C3%A4r-leken-blev-allvar?video_id=3596575

I use Version 55.0.2883.95 (64-bit) on mac

**Comment by bubach** [comment]
I use the exact same version, 64-bit mac, and I did not have any problems with that video.  Do you also use other adblock software?  Try disabling that.
